version: '3.8'

services:
  app:
    image: openjdk:8-jdk-alpine
    container_name: java-app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DB_URL=jdbc:postgresql://movie-star-wars.railway.internal:5432/movie_db
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    ports:
      - "8080:8080"
    command: ["./mvnw", "spring-boot:run"]

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "client_encoding=UTF8" ]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"